name: task_management
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # ALL OTHER PACKAGES
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  get: ^4.6.5
  pinput: ^3.0.1
  gap: ^3.0.1
  auto_size_text_field: ^2.2.2
  country_picker: ^2.0.27
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  device_info_plus: ^11.2.1
  universal_io: ^2.2.2
  intl: ^0.20.1
  connectivity_plus: ^6.1.2
  cloud_firestore: ^5.6.2
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: any
  build_runner: ^2.2.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
